version: '3'
services:
  proxy:
    build: ./proxy/
    ports:
      - "1080:1080"
    networks:
      - db
      - internal_net
    cap_add:
      - CAP_NET_RAW
    depends_on:
      - db

  web:
    build: ./web/

    ports:
      - 9145:80
    networks:
      - db

  db:
    image: mariadb:latest
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./data/:/var/lib/mysql:Z
    environment:
      MARIADB_ALLOW_EMPTY_ROOT_PASSWORD: "true"
    networks:
      - db
      - db2

  echo:
    build: ./echo/
    networks:
      - internal_net

  premium-forum:
    build: ./forum/
    environment:
      DATABASE_URL: "mysql://premium_forum@db/premium_forum"
    networks:
      - db2
      - internal_net
    depends_on:
      - db


networks:
  db:
  db2:

  internal_net:
    name: test
    internal: true
    attachable: true
    driver_opts:
      'com.docker.network.container_iface_prefix': "asd"

