version: '3'
services:
  proxy:
    build: ./proxy/
    volumes:
      - ./data/proxy:/data:rw
    ports:
      - 1080

  db:
    image: mariadb:latest
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./data/db/:/var/lib/mysql:Z
    environment:
      MARIADB_ALLOW_EMPTY_ROOT_PASSWORD: true

