version: '3'
services:
  proxy:
    build: ./proxy/
    # The code should be copied into the container using COPY.
    # Mount the data folder writable, so that information can be persisted across restarts.
    volumes:
      - ./data/proxy:/data:rw
    # Define the port mapping (external:internal port)
    ports:
      - 1080
