version: '3'
services:
  onlyflags-checker:
    build: .
    # The checker runs a HTTP interfaces, so we need to map port 3031 to the outside (port 8000).
    ports:
      - 5008:8000
    environment:
     - MONGO_ENABLED=1
     - MONGO_HOST=onlyflags-mongo
     - MONGO_PORT=27017
     - MONGO_USER=onlyflags_checker
     - MONGO_PASSWORD=onlyflags_checker
    mem_limit: 1G
    memswap_limit: 2G
    ulimits:
      core:
        soft: 0
        hard: 0
      nproc:
        soft: 4000
        hard: 4000

  onlyflags-mongo:
    image: mongo
      #volumes:
      #- ./data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: onlyflags_checker
      MONGO_INITDB_ROOT_PASSWORD: onlyflags_checker
    mem_limit: 1G
    memswap_limit: 2G
    ulimits:
      core:
        soft: 0
        hard: 0
      nproc:
        soft: 4000
        hard: 4000
